name: Deploy Weather App  

on:  
  push:  
    branches: [ main ]  # Runs on push to the main branch  
  workflow_dispatch:    # Allows manual trigger  

jobs:  
  deploy:  
    runs-on: self-hosted  # Uses your self-hosted runner  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Login to Docker Hub  
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  

      - name: Build and Push Docker Image  
        run: |  
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-app:latest .  
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-app:latest  

      - name: SSH into Server and Deploy  
        uses: appleboy/ssh-action@v0.1.7  
        with:  
          host: ${{ secrets.SERVER_IP }}  
          username: ${{ secrets.SERVER_USERNAME }}  
          password: ${{ secrets.SERVER_PASSWORD }}  
          script: |  
            docker pull ${{ secrets.DOCKER_USERNAME }}/weather-app:latest  
            docker stop weather-app || true  
            docker rm weather-app || true  
            docker run -d -p 80:80 --name weather-app ${{ secrets.DOCKER_USERNAME }}/weather-app:latest  
