jobs:
  deploy:
    runs-on: self-hosted  # Uses your self-hosted runner on Ubuntu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.MY_DOCKER_USER }}" --password-stdin

      - name: Pull and Run Docker Container
        run: |
          docker pull ${{ secrets.MY_DOCKER_USER }}/weather-report:latest
          docker stop weather-app || true
          docker rm weather-app || true
          docker run -d --name weather-app -p 80:80 ${{ secrets.MY_DOCKER_USER }}/weather-report:latest
