name: Deploy Application

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest  # or any other OS you prefer
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MY_DOCKER_USER }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Your Docker Hub password

      - name: Run deployment script on server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            echo "Deploying the application"
            # Add your deployment commands here, e.g.
            # cd /path/to/your/project
            # git pull origin main
            # docker-compose up -d
          EOF
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Server's IP
          SERVER_USER: ${{ secrets.SERVER_USER }}  # Ubuntu username
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}  # Ubuntu password
