name: Deploy Application

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest  # or any other OS you prefer
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MY_DOCKER_USER }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Your Docker Hub password (stored in secrets)

      - name: Set up SSH for deployment
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}  # Replace with your server's IP address or use the secret
          username: ${{ secrets.SERVER_USER }}  # Replace with your Ubuntu username (e.g., abhijeeth-manakan)
          password: ${{ secrets.SERVER_PASSWORD }}  # Replace with your Ubuntu password (or use a secure method like SSH key)
          port: 22
          script: |
            echo "Deploying the application"
            # Add your deployment commands here, e.g.
            # cd /path/to/your/project
            # git pull origin main
            # docker-compose up -d
          timeout: 60s  # Increase timeout for SSH connection
          use_insecure_cipher: false
          debug: true  # Set to true for debugging information if needed
