name: Deploy Weather-Report App

on:
  push:
    branches:
      - main  # Runs this workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Uses an Ubuntu virtual machine for the build process

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Fetches the latest code from GitHub

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enables advanced Docker features

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER}}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/weatherapp:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weatherapp:latest

  deploy:
    needs: build  # Ensures deployment happens after the build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          private_key: ${{ secrets.SERVER_SSH_KEY }}  # Use the SSH private key stored in GitHub secrets
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/weatherapp:latest
            docker stop weather-container || true
            docker rm weather-container || true
            docker run -d --name weather-container -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/weatherapp:latest
