name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install sshpass (needed for passing password via ssh)
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # Step 3: Run deployment script on your Ubuntu server
      - name: Run deployment script on server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" << 'EOF'
          # Deployment commands
          echo "Deploying the application"

          # Example deployment commands (replace with your own)
          cd /path/to/your/project
          git pull origin main
          docker-compose up -d
          
          # Other commands you might want to run during deployment
          EOF

        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
